name: basedpl-jupyterlite
channels:
  - conda-forge
dependencies:
  - python=3.12
  - nodejs=22
  - jupyterlite-core=0.7.6
  - jupyterlab=4.5.11
  - jupyter_server
  - hatchling>=1.5
  - hatch-jupyter-builder>=0.5
  - hatch-nodejs-version>=0.3.2
